#! /nix/store/hm8sxwvz7qbf5kzgprdlggj231l5g2s4-bash-5.2-p15/bin/bash -e
export DEPS_CLJ_TOOLS_DIR=${DEPS_CLJ_TOOLS_DIR-'/nix/store/6an35qmzsdp84kamww5mg65f56139xax-babashka-1.3.184/clojure_tools'}
export DEPS_CLJ_TOOLS_VERSION=${DEPS_CLJ_TOOLS_VERSION-'1.11.1.1413'}
export JAVA_HOME=${JAVA_HOME-'/nix/store/0ps3v7cram6911gazmq76nxsq5fmccma-zulu17.44.15-ca-jdk-17.0.8'}
exec -a "$0" "/nix/store/3c6p6g0ns5pds4s3r19zhv0gzcm70yba-babashka-unwrapped-1.3.184/bin/bb"  "$@" 
